set  nu             " show line numbers
syn  on
set cursorline      " highlight current line
set syntax=on
set history=1000    " keep track of history for 1000 actions
set shiftwidth=2    " indent operations produce 2 columns space
set tabstop=2       " hitting tab produces 4 columns space

"set incsearch       " incremental searching
"set hlsearch        " highlight searchresult

set scrolloff=4     " keep at least 4 lines above or below the cursor

" fileformat stuff
set fileformats=unix
set encoding=utf-8
set fileencodings=utf-8


" Always show statusbar
set laststatus=2
set background=dark

let mapleader="," " leader

