# Path
export PATH="$(brew --prefix php70)/bin:$PATH"
export PATH="/usr/local/opt/go/libexec/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
export PATH="$HOME/.composer/vendor/bin:$PATH"
export PATH="$PATH:/usr/local/opt/go/libexec/bin"
export GOPATH="$HOME/workspace/goprojects"
export PATH="$PATH:$GOPATH/bin"
export RBENV_ROOT=/usr/local/var/rbenv
export EDITOR='nvim'

#Tmuxinator
export DISABLE_AUTO_TITLE=true
